export const USER_SIGN_IN_COMPLETE = 'USER_SIGN_IN_COMPLETE';

export const WORK_SETTINGS_FETCH_COMPLETE = 'WORK_SETTINGS_FETCH_COMPLETE';
export const WORK_SETTINGS_UPDATE_COMPLETE = 'WORK_SETTINGS_UPDATE_COMPLETE';
